/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlightMotor_System;

import java.sql.DriverManager;
import static java.sql.DriverManager.getConnection;
import java.io.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.util.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import javax.imageio.ImageIO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Ayesh Perera
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
   
    private InputStream in;
    private Object DbUtils;
    private String srcch;
    
    Main mn=new Main();
    
    
    public Employee() {
        initComponents();
        Show_data_Table();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fhead = new javax.swing.JLayeredPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jrembtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        uaddbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jsearch1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jemptble = new javax.swing.JTable();
        jcmbo1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        fhead.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout fheadLayout = new javax.swing.GroupLayout(fhead);
        fhead.setLayout(fheadLayout);
        fheadLayout.setHorizontalGroup(
            fheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fheadLayout.setVerticalGroup(
            fheadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("Close Window");
        jButton1.setActionCommand("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jrembtn.setText("Delete User");
        jrembtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrembtnActionPerformed(evt);
            }
        });

        jButton2.setText("Admins");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Garage Employees");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("Service Employees");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Office Employees");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Update User");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        uaddbtn.setText("Add New");
        uaddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uaddbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uaddbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jrembtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uaddbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrembtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jrembtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(uaddbtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Panel");

        jDesktopPane1.setName(""); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search by Employee id");

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("View All");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        Jemptble.setAutoCreateRowSorter(true);
        Jemptble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Id", "Employee Name", "Section", "Address", "Con_Number", "Assigned Date", "Basic Salary", "Gender"
            }
        ));
        jScrollPane1.setViewportView(Jemptble);

        jcmbo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emp id", "emp name", "section" }));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Select Search Category");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(jcmbo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jsearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsearch1)
                    .addComponent(jcmbo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jDesktopPane1.setLayer(jsearch1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jcmbo1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(fhead)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                        .addComponent(fhead))
                    .addContainerGap(649, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    public ArrayList<EmployeeT> getUserList(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee`";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
     public ArrayList<EmployeeT> getofUserList(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `Section` LIKE 'office'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
     
     public ArrayList<EmployeeT> getserUserList(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `Section` LIKE 'service'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
    public ArrayList<EmployeeT> getgarUserList(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `Section` LIKE 'garage'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
            
            
            
            
            
            
            
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
    public ArrayList<EmployeeT> getadmUserList(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `Section` LIKE 'admin'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
    public ArrayList<EmployeeT> gettableinfo1(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `E_Id` LIKE '"+srcch+"'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
    public ArrayList<EmployeeT> gettableinfo2(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `E_Name` LIKE '%"+srcch+"%'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
    
    public ArrayList<EmployeeT> gettableinfo3(){
        
        ArrayList userlist=new ArrayList();
        
        Connection con=mn.getcon();
        
        String qyr="SELECT * FROM `employee` WHERE `Section` LIKE '%"+srcch+"%'";
        Statement st;
        ResultSet rs;
        
        try{
            st=con.createStatement();
            rs=st.executeQuery(qyr);
            
            EmployeeT empt;
            
            while(rs.next()){
                
                empt=new EmployeeT(rs.getInt("E_Id"),rs.getString("E_Name"),rs.getString("Section"),rs.getString("Address"),rs.getString("T_Nmbr"),rs.getDate("Ass_Date"),rs.getInt("Ba_Sal"),rs.getString("Gender"),rs.getString("Password"));
                userlist.add(empt);
            }
                    
        }catch(Exception e){
            
            e.printStackTrace();
            
        }
        return userlist;
        
    }
     
    public void Show_data_Table()
    {
        ArrayList<EmployeeT> list=getUserList();
        DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getsect();
            row[3]=list.get(i).getAdr();
            row[4]=list.get(i).getTnmbr();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getsal();
            row[7]=list.get(i).getGen();
            
            model.addRow(row);
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jrembtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrembtnActionPerformed
        // TODO add your handling code here:
        new deleteuser().setVisible(true);
        
    }//GEN-LAST:event_jrembtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:office users
        
        
        
         ArrayList<EmployeeT> list=getofUserList();
        DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getsect();
            row[3]=list.get(i).getAdr();
            row[4]=list.get(i).getTnmbr();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getsal();
            row[7]=list.get(i).getGen();
            
            model.addRow(row);
        }
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:service users
        
          ArrayList<EmployeeT> list=getserUserList();
        DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getsect();
            row[3]=list.get(i).getAdr();
            row[4]=list.get(i).getTnmbr();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getsal();
            row[7]=list.get(i).getGen();
            
            model.addRow(row);
        }
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ArrayList<EmployeeT> list=getgarUserList();
        DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getsect();
            row[3]=list.get(i).getAdr();
            row[4]=list.get(i).getTnmbr();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getsal();
            row[7]=list.get(i).getGen();
            
            model.addRow(row);
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ArrayList<EmployeeT> list=getadmUserList();
        DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getName();
            row[2]=list.get(i).getsect();
            row[3]=list.get(i).getAdr();
            row[4]=list.get(i).getTnmbr();
            row[5]=list.get(i).getDate();
            row[6]=list.get(i).getsal();
            row[7]=list.get(i).getGen();
            
            model.addRow(row);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        Show_data_Table();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        srcch=jsearch1.getText();
        int indx=jcmbo1.getSelectedIndex();
        
        //JOptionPane.showMessageDialog(rootPane,srcch + " - " + indx);
        
        if(indx==0){
            
            ArrayList<EmployeeT> list=gettableinfo1();
            DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
            model.setRowCount(0);
            Object[] row = new Object[8];
            for(int i=0;i<list.size();i++)
            {
                row[0]=list.get(i).getid();
                row[1]=list.get(i).getName();
                row[2]=list.get(i).getsect();
                row[3]=list.get(i).getAdr();
                row[4]=list.get(i).getTnmbr();
                row[5]=list.get(i).getDate();
                row[6]=list.get(i).getsal();
                row[7]=list.get(i).getGen();

                model.addRow(row);
            }
            
        }
        
        else if(indx==1){
            
            ArrayList<EmployeeT> list=gettableinfo2();
            DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
            model.setRowCount(0);
            Object[] row = new Object[8];
            for(int i=0;i<list.size();i++)
            {
                row[0]=list.get(i).getid();
                row[1]=list.get(i).getName();
                row[2]=list.get(i).getsect();
                row[3]=list.get(i).getAdr();
                row[4]=list.get(i).getTnmbr();
                row[5]=list.get(i).getDate();
                row[6]=list.get(i).getsal();
                row[7]=list.get(i).getGen();

                model.addRow(row);
            }
            
        }
       
        else if(indx==2){
            
            ArrayList<EmployeeT> list=gettableinfo3();
            DefaultTableModel model=(DefaultTableModel)Jemptble.getModel();
            model.setRowCount(0);
            Object[] row = new Object[8];
            for(int i=0;i<list.size();i++)
            {
                row[0]=list.get(i).getid();
                row[1]=list.get(i).getName();
                row[2]=list.get(i).getsect();
                row[3]=list.get(i).getAdr();
                row[4]=list.get(i).getTnmbr();
                row[5]=list.get(i).getDate();
                row[6]=list.get(i).getsal();
                row[7]=list.get(i).getGen();

                model.addRow(row);
            }
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void uaddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uaddbtnActionPerformed
        // TODO add your handling code here:
        new UserAdd().setVisible(true);
    }//GEN-LAST:event_uaddbtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        new userupdate().setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Jemptble;
    private javax.swing.JLayeredPane fhead;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox jcmbo1;
    private javax.swing.JButton jrembtn;
    private javax.swing.JTextField jsearch1;
    private javax.swing.JButton uaddbtn;
    // End of variables declaration//GEN-END:variables
}
